import {suggestCategory,extractDate} from './slip-fields.mjs';
import {parseSlip,validateExpense,csvExport} from './ledger.mjs';
const $=id=>document.getElementById(id),KEY='slip-ledger-v1';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const money=c=>new Intl.NumberFormat('en-TH',{style:'currency',currency:'THB'}).format(c/100);
let entries=[],editing=null,previewUrl=null,slipHash='',busy=false,worker=null,scanToken=0,deleteId=null,toastTimer,storageBroken=false;
$('month').value=today().slice(0,7);
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',5000);}
try{const raw=localStorage.getItem(KEY);if(raw){const data=JSON.parse(raw);if(!Array.isArray(data))throw Error();entries=data.map(validateExpense);}}catch{storageBroken=true;$('scanStatus').textContent='Saved data could not be read. Restore a valid backup to recover it; existing storage will not be overwritten.';}
function commit(next){if(storageBroken)throw Error('Restore a valid backup before saving new expenses.');localStorage.setItem(KEY,JSON.stringify(next));entries=next;render();}
function selected(){return entries.filter(e=>e.date.startsWith($('month').value)).sort((a,b)=>b.date.localeCompare(a.date));}
function cell(text,tag='td',className=''){const el=document.createElement(tag);el.textContent=text;el.className=className;return el;}
function render(){
 const rows=selected(),total=rows.reduce((n,e)=>n+e.cents,0),groups={};for(const e of rows)groups[e.category]=(groups[e.category]||0)+e.cents;const sorted=Object.entries(groups).sort((a,b)=>b[1]-a[1]);
 const [year,month]=$('month').value.split('-').map(Number);$('monthLabel').textContent=new Date(year,month-1,1).toLocaleDateString('en-GB',{month:'short',year:'numeric'});$('total').textContent=money(total);$('count').textContent=rows.length?`${rows.length} reviewed expense${rows.length===1?'':'s'}`:'No expenses this month';$('topCategory').textContent=sorted[0]?.[0]||'—';$('topAmount').textContent=sorted.length?`${money(sorted[0][1])} · ${Math.round(sorted[0][1]/total*100)}% of spending`:'Add an expense to see your breakdown';const days=$('month').value===today().slice(0,7)?new Date().getDate():new Date(year,month,0).getDate();$('average').textContent=money(Math.round(total/days));$('averageHint').textContent=`Across ${days} calendar days`;
 $('expenses').replaceChildren();for(const e of rows){const tr=document.createElement('tr'),payment=cell('');payment.append(cell(e.recipient,'strong'),cell(new Date(e.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}),'small'));if(e.note)payment.append(cell(e.note,'small'));const category=cell('');category.append(cell(e.category,'span','category-tag'));const actions=cell(''),wrap=cell('','div','row-actions');for(const [label,fn]of[['Edit',()=>openReview(e)],['Delete',()=>{deleteId=e.id;$('deleteDialog').showModal();}]]){const b=cell(label,'button','row-button');b.setAttribute('aria-label',`${label} ${e.recipient}`);b.onclick=fn;wrap.append(b);}actions.append(wrap);tr.append(payment,category,cell(money(e.cents),'td','number'),actions);$('expenses').append(tr);}
 $('empty').hidden=rows.length>0;$('resultCount').textContent=`${rows.length} expense${rows.length===1?'':'s'}`;$('exportCsv').disabled=!rows.length;$('categoryBars').replaceChildren();if(!sorted.length)$('categoryBars').append(cell('Your category breakdown will appear here.','p','subtle'));for(const [category,value]of sorted){const row=cell('','div','bar-row'),label=cell('','div','bar-label'),track=cell('','div','bar-track'),bar=cell('','div','bar-fill');label.append(cell(category,'span'),cell(money(value),'span'));bar.style.width=`${value/total*100}%`;track.append(bar);row.append(label,track);$('categoryBars').append(row);}
}
function releasePreview(){if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=null;$('slipPreview').removeAttribute('src');$('slipPreview').hidden=true;}
const categoryHint=document.createElement('p');categoryHint.className='subtle';categoryHint.id='categoryHint';categoryHint.style.fontSize='14px';$('category').parentElement.append(categoryHint);$('category').setAttribute('aria-describedby','categoryHint');
let categoryChosen=false;
function updateCategorySuggestion(){if(editing||categoryChosen)return;const suggestion=suggestCategory($('recipient').value,entries);$('category').value=suggestion.category;categoryHint.textContent=suggestion.reason;}
$('recipient').addEventListener('input',updateCategorySuggestion);
$('category').addEventListener('change',()=>{categoryChosen=true;categoryHint.textContent='Your category choice will be remembered after saving.';});
function openReview(entry=null,scan=null){
 editing=entry?.id||null;categoryChosen=false;slipHash=entry?.slipHash||scan?.hash||'';$('expenseForm').reset();$('formError').textContent='';$('reviewTitle').textContent=entry?'Edit expense':scan?'Review detected details':'Add expense';$('recipient').value=entry?.recipient||scan?.recipient||'';$('amount').value=entry?(entry.cents/100).toFixed(2):scan?.amount||'';$('date').value=entry?.date||(scan?scan.date:today());$('category').value=entry?.category||'Other';$('note').value=entry?.note||'';$('ocrDetails').hidden=!scan?.text;$('ocrText').textContent=scan?.text||'';
 if(!scan)releasePreview();
 const missing=scan?[!scan.date?'date':null,!scan.recipient?'recipient':null,!scan.amount?'amount':null].filter(Boolean):[];
 $('reviewHint').textContent=scan?(missing.length?`Could not confidently read the ${missing.join(', ')}. Check the slip image and fill in the missing details. `:'')+'Check all suggestions against your slip before saving.':'Check the amount, date and recipient before saving.';
 categoryHint.textContent=entry?'Change the category if needed.':'';updateCategorySuggestion();$('review').showModal();
}
$('manual').onclick=()=>openReview();$('closeReview').onclick=$('discard').onclick=()=>$('review').close();$('review').addEventListener('close',releasePreview);
$('expenseForm').onsubmit=e=>{e.preventDefault();try{const entry=validateExpense({id:editing||crypto.randomUUID(),recipient:$('recipient').value.trim(),cents:Math.round(Number($('amount').value)*100),date:$('date').value,category:$('category').value,note:$('note').value.trim(),slipHash});if(slipHash&&entries.some(e=>e.id!==editing&&e.slipHash===slipHash))throw Error('This exact slip is already saved. Edit the original expense instead.');commit(editing?entries.map(e=>e.id===editing?entry:e):[...entries,entry]);$('month').value=entry.date.slice(0,7);render();$('review').close();toast('Expense saved on this device.');}catch(err){$('formError').textContent=err.message||'Could not save. Your browser storage may be full.';}};
$('month').onchange=()=>{if(!$('month').value)$('month').value=today().slice(0,7);render();};$('keepExpense').onclick=()=>$('deleteDialog').close();$('confirmDelete').onclick=()=>{try{commit(entries.filter(e=>e.id!==deleteId));$('deleteDialog').close();toast('Expense deleted.');}catch{toast('Could not delete. Check browser storage access.');}};
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportCsv').onclick=()=>download(`expenses-${$('month').value}.csv`,csvExport(selected()),'text/csv;charset=utf-8');$('backup').onclick=()=>download(`slip-ledger-${today()}.json`,JSON.stringify({version:1,currency:'THB',expenses:entries},null,2),'application/json');$('restore').onclick=()=>$('backupFile').click();
$('backupFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>10*1024*1024)throw Error('Backup is too large (maximum 10 MB).');const data=JSON.parse(await file.text());if(data.version!==1||data.currency!=='THB'||!Array.isArray(data.expenses))throw Error('Choose a Slip Ledger backup file.');const incoming=data.expenses.map(validateExpense),merged=new Map(entries.map(e=>[e.id,e]));let added=0;for(const entry of incoming){if(!merged.has(entry.id)&&![...merged.values()].some(e=>e.slipHash&&e.slipHash===entry.slipHash)){merged.set(entry.id,entry);added++;}}const next=[...merged.values()];localStorage.setItem(KEY,JSON.stringify(next));entries=next;storageBroken=false;render();$('scanStatus').textContent='';toast(`Restored ${added} expenses. Existing entries were kept.`);}catch(err){toast(err.message||'Could not restore backup.');}};
function setBusy(value){busy=value;$('slipFile').disabled=value;$('manual').disabled=value;$('language').disabled=value;$('scanProgress').hidden=!value;$('cancelScan').hidden=!value;$('dropzone').setAttribute('aria-busy',String(value));}
async function loadOcr(){if(window.Tesseract)return window.Tesseract;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js';script.onload=resolve;script.onerror=()=>{script.remove();reject(Error('Reader download failed'));};document.head.append(script);});return window.Tesseract;}
async function readSlip(file){
 if(busy||!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('Choose a JPG, PNG or WebP image.');return;}if(file.size>10*1024*1024){toast('Choose an image smaller than 10 MB.');return;}const token=++scanToken;setBusy(true);$('scanStatus').textContent='Preparing reader… First use downloads Thai and English language files.';$('scanProgress').value=0;releasePreview();let timer;
 try{const buffer=await file.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',buffer))].map(b=>b.toString(16).padStart(2,'0')).join('');if(token!==scanToken)return;if(entries.some(e=>e.slipHash===hash)){toast('This exact slip is already saved.');$('scanStatus').textContent='Duplicate slip: no new expense added.';return;}
 previewUrl=URL.createObjectURL(file);const img=new Image();img.src=previewUrl;await img.decode();if(img.width*img.height>40000000)throw Error('Image too large');const scale=Math.min(1,2400/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);
 const work=async()=>{
  const ocr=await loadOcr();if(token!==scanToken)return null;
  const current=await ocr.createWorker($('language').value,1,{logger:m=>{if(token!==scanToken)return;if(m.status==='recognizing text'){$('scanStatus').textContent=`Reading slip… ${Math.round(m.progress*100)}%`;$('scanProgress').value=Math.round(m.progress*100);}else $('scanStatus').textContent='Loading the slip reader… This may take a minute on first use.';}});
  if(token!==scanToken){await current.terminate();return null;}worker=current;
  const result=await current.recognize(canvas),text=result.data.text,parsed=parseSlip(text);let headerText='';
  if(!parsed.date&&token===scanToken){
   $('scanStatus').textContent='Taking a closer look at the date…';
   // Enlarge the header and improve contrast for small Thai date labels.
   const header=document.createElement('canvas'),factor=Math.min(3,3000/canvas.width),height=Math.round(canvas.height*.35);
   header.width=Math.round(canvas.width*factor);header.height=Math.round(height*factor);
   const hctx=header.getContext('2d');hctx.filter='grayscale(1) contrast(1.35)';hctx.drawImage(canvas,0,0,canvas.width,height,0,0,header.width,header.height);
   try{await current.setParameters({tessedit_pageseg_mode:'6'});const retry=await current.recognize(header);headerText=retry.data.text;parsed.date=extractDate(headerText);}catch{/* Keep the initial result when the optional closer read fails. */}
  }
  return {parsed,text:text+(headerText?'\n\nDate close-up:\n'+headerText:'')};
 };
 const result=await Promise.race([work(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Reader timed out')),150000);})]);if(token!==scanToken||result===null)return;
 const {parsed,text}=result;$('slipPreview').src=previewUrl;$('slipPreview').hidden=false;$('scanStatus').textContent=text.trim()?'Slip read. Review the details before saving.':'No readable text found. Enter the details from your slip.';openReview(null,{...parsed,text,hash});
 }catch{if(token===scanToken){$('scanStatus').textContent='Could not read this image. Check your connection, try a clearer image, or add it manually.';releasePreview();}}finally{clearTimeout(timer);if(token===scanToken){++scanToken;if(worker){worker.terminate().catch(()=>{});worker=null;}setBusy(false);$('slipFile').value='';}}
}
$('cancelScan').onclick=()=>{++scanToken;if(worker){worker.terminate().catch(()=>{});worker=null;}releasePreview();setBusy(false);$('slipFile').value='';$('scanStatus').textContent='Reading canceled. No expense was saved.';};$('slipFile').onchange=e=>readSlip(e.target.files[0]);for(const event of ['dragenter','dragover'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.add('dragover');});for(const event of ['dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.remove('dragover');});$('dropzone').addEventListener('drop',e=>readSlip(e.dataTransfer.files[0]));
window.addEventListener('storage',e=>{if(e.key===KEY){try{const raw=e.newValue?JSON.parse(e.newValue):[];if(!Array.isArray(raw))throw Error();entries=raw.map(validateExpense);storageBroken=false;render();}catch{storageBroken=true;toast('Saved data changed unexpectedly. Restore a backup to recover.');}}});render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'stage_expense_review',description:'Open an expense draft for user review. Does not save it.',inputSchema:{type:'object',properties:{recipient:{type:'string'},amount:{type:'number'},date:{type:'string'}},required:['recipient','amount','date'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(busy||$('review').open)throw Error('Finish the current review first.');const draft=validateExpense({id:'draft',recipient:input.recipient,cents:Math.round(input.amount*100),date:input.date,category:'Other',note:''});openReview();$('recipient').value=draft.recipient;$('amount').value=(draft.cents/100).toFixed(2);$('date').value=draft.date;updateCategorySuggestion();return {status:'awaiting_user_review',saved:false};}})).catch(()=>{});}catch{}}


